name: Zicops Flutter CI-CD<>Formec App Bundle

on:
 workflow_dispatch:
  #push:
   # branches:
    #  - main
  #pull_request:
   # branches:
    #  - main

jobs:
 
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
 
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
      - run: flutter clean
      - run: flutter pub get
      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      #- run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
      - run: flutter clean
      - run: flutter pub get
      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-ios-${{ hashFiles('**/pubspec.lock') }}
      - run: flutter build ios --release --no-codesign
      - name: Cache outputs of build step
        uses: actions/cache@v2
        with:
          path: build/ios/iphoneos
          key: apple-${{ github.sha }}

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
      - run: flutter clean
      - run: flutter pub get
      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-ios-${{ hashFiles('**/pubspec.lock') }}
      - run: flutter build apk --release --split-per-abi
      - name: Cache outputs of build step
        uses: actions/cache@v2
        with:
          path: build/app/outputs/apk/release
          key: android-${{ github.sha }}

  upload_apps_artifacts:
    name: Upload Zicops Flutter Bundles
    needs: [build_appbundle, build_ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the apk file from cache
        uses: actions/cache@v2
        with:
          path: build/app/outputs/apk/release
          key: android-${{ github.sha }}
      - name: Get the ipa file from cache
        uses: actions/cache@v2
        with:
          path: build/ios/iphoneos
          key: apple-${{ github.sha }}
      - name: Upload Android bundle
        uses: actions/upload-artifact@v2
        with:
          name: android_bundle
          path: build/app/outputs/apk/release
      - name: Upload iOS bundle
        uses: actions/upload-artifact@v2
        with:
          name: apple_bundle
          path: build/ios/iphoneos
